### ISSUE TITLE
Thread replies aren't consistently ordering chronologically

### ISSUE THREAD

**Issue by hartsick** [hartsick/fantastic-broccoli#16]
See this thread https://rubby-forum-production.herokuapp.com/topics/19

**Comment by killpack** [comment]
Oh, it looks like posts aren't being explicitly sorted at all! https://github.com/hartsick/fantastic-broccoli/blob/main/app/views/topics/show.html.erb#L8 So I guess you get them back in whatever order the database feels like. 

Maybe all we need is to change `@topic.posts` to `@topic.posts.order(:created_at)`?

**Comment by hartsick** [comment]
#jordansright

**Comment by hartsick** [comment]
(we're committing to main here so no PR but the fix is what you suggested!)
