### ISSUE TITLE
"Favorite food" is appearing as a prompt for user profile, but does not appear as a title when viewing someone's profile

### ISSUE THREAD

**Issue by stephengoldmeier** [hartsick/fantastic-broccoli#18]
Not sure if this is a bug or just using "favorite food" as a placeholder for more general profile prompt?

**Comment by hartsick** [comment]
it's kind of both since I just forgot to put a label! what do you want it to be?

**Comment by stephengoldmeier** [comment]
after sitting with it, i do think it's kind of funny that the "profile info" is "favorite food" and you can just put whatever you want. but as a new user, i was confused. 

"profile" is possibly too plain / boring.

maybe "away message" still captures the nostalgic feeling, is a little jokey, but signals that it's just general profile stuff?

**Comment by hartsick** [comment]
i like it

**Comment by hartsick** [comment]
I swapped out the prompt for "whatever you want here:" and then restyled the profile page. it felt kind of weird to label the response to me since there's just one field on the page, idk. let me know if it still feels weird or confusing!
